# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from group import Group


class TestTestaddgroup():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_add_group(self):
        self.open_home_page()
        self.login(user="admin", password="secret")
        self.open_group_page()
        self.create_group(Group(name="1", header="2", footer="3"))
        self.return_group_page()
        self.logout()

    def test_add_empty_group(self):
        self.open_home_page()
        self.login(user="admin", password="secret")
        self.open_group_page()
        self.create_group(Group(name="", header="", footer=""))
        self.return_group_page()
        self.logout()

    def open_home_page(self):
        self.driver.get("http://localhost/addressbook/")
        self.driver.maximize_window()

    def login(self, user, password):
        self.driver.find_element(By.NAME, "user").click()
        self.driver.find_element(By.NAME, "user").clear()
        self.driver.find_element(By.NAME, "user").send_keys(user)
        self.driver.find_element(By.NAME, "pass").click()
        self.driver.find_element(By.NAME, "pass").clear()
        self.driver.find_element(By.NAME, "pass").send_keys(password)
        self.driver.find_element(By.CSS_SELECTOR, "input[type=\"submit\"]").click()

    def open_group_page(self):
        self.driver.find_element(By.LINK_TEXT, "groups").click()

    def create_group(self, group):
        # init group creation
        self.driver.find_element(By.NAME, "new").click()
        # fill form
        self.driver.find_element(By.NAME, "group_name").click()
        self.driver.find_element(By.NAME, "group_name").clear()
        self.driver.find_element(By.NAME, "group_name").send_keys(group.name)
        self.driver.find_element(By.NAME, "group_header").click()
        self.driver.find_element(By.NAME, "group_header").clear()
        self.driver.find_element(By.NAME, "group_header").send_keys(group.header)
        self.driver.find_element(By.NAME, "group_footer").click()
        self.driver.find_element(By.NAME, "group_footer").clear()
        self.driver.find_element(By.NAME, "group_footer").send_keys(group.footer)
        self.driver.find_element(By.NAME, "submit").click()

    def return_group_page(self):
        self.driver.find_element(By.LINK_TEXT, "group page").click()

    def logout(self):
        self.driver.find_element(By.LINK_TEXT, "Logout").click()
